### PR TITLE
Feature/consistency and spelling

### PR DESCRIPTION
**Pull request by jrfnl**
Changes are along the lines of:
- Correcting grammer and spelling errors
- Fix some blatant copy/paste errors
- Removing PHP closing tags if not needed to demonstrate a point (to be in line with the no-closing-tags rule)
- Removing unused/commented out headers (to be in line with no-commented-out-code rule - lead by example)
- Small markdown use improvements, mainly for consistency:
  - adding code backticks
  - removing code backticks from non code phrases, replacing them by underscores to make the text cursive
  - make functions in phrases always have `()`, and remove them for most language constructs 
  - consistent use of bullets and fixed where they would not be recognized as such
  - simplify table layouts
- Added some additional _Further Reading_ links
- Make links to PHP manual language agnostic

As this is quite a huge PR, I have purposefully split it in functional commits for easier review. Please see the notes on the individual commits for more information.

### CODE REVIEW

**Comment by dseguy** [comment]
Juliette : 

Removing PHP closing tags if not needed to demonstrate a point (to be in line with the no-closing-tags rule)

I'd like to keep them when in documentation (See contributing).

**Comment by jrfnl** [comment]
I could just adjust the PR to bring them back ? Why close it - this PR is about a lot more than just that...

**Comment by jrfnl** [comment]
@dseguy How do you want to continue with this ? Do you want to cherry-pick the individual commits ?
Do you want me to send in a new PR without removing the closing tags ? (Though I still feel a rule library like this should lead by example)

Or maybe sit down an afternoon ?

Leaving this for much longer will make keeping up with the changes very hard for the next PR ...

**Comment by dseguy** [comment]
Hi Juliette,

Yes, I'm a bit lost here on the next step.
Do you have time for a quick call?

Damien

**Comment by jrfnl** [comment]
@dseguy Hi Damien,

Yes please, Monday afternoon a good time for you ?

Smile,
Juliette

**Pull request closed without merging**
